services:
    oraclefree:
        image: ghcr.io/gvenzl/oracle-free:23.7-faststart
        ports:
            - 1521:1521
        environment:
            ORACLE_PASSWORD: free
            APP_USER: developer
            APP_USER_PASSWORD: free
        volumes:
            - ora_db_vol:/opt/oracle/oradata
        networks:
            - ora_app_network
        healthcheck:
            test: [ "CMD", "/opt/oracle/healthcheck.sh" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s

    ords:
        depends_on:
            oraclefree:
                condition: service_healthy

        image: loiclefevre/ords-ol8:latest
        environment:
            DB_HOSTNAME: devcontainer-oraclefree-1
            DB_SERVICE: freepdb1
            SYS_PASSWORD: free
        networks:
            - ora_app_network
        ports:
            - 27017:27017
            - 8080:8080
            - 8443:8443

volumes:
    ora_db_vol:
    ords_config_vol:

networks:
    ora_app_network:
